# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "<i class=\"fas fa-home\"></i> Home"
  url = ""
  weight = 5

[[main]]
  name = "<i class=\"fas fa-file\"></i> Posts"
  url = "#posts"
  weight = 10

#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

[[main]]
  name = "<i class=\"fas fa-chart-area\"></i> Visualizations"
  url = "https://github.com/jtlawren67/data_visualizations"
  weight = 20

[[main]]
  name = "<i class=\"fas fa-user\"></i> About"
  url = "#about"
  weight = 40

[[main]]
  name = "<i class=\"fas fa-rss\"></i> RSS"
  url = "/category/r/index.xml"
  weight = 45
  
[[main]]
  name = "<i class=\"fab fa-github\"></i> Github"
  url = "https://github.com/jtlawren67"
  weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
