---
title: Does Icing the Kicker Really Work?
author: JLaw
date: '2022-02-14'
slug: does-icing-the-kicker-really-work
categories:
  - R
  - CausalInference
tags:
  - survey
  - broom
  - gtsummary
  - rsample
  - smd
subtitle: ''
summary: ''
authors: []
lastmod: '2022-01-29T18:49:23-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<p>In my prior post I <a href="https://jlaw.netlify.app/2022/01/24/predicting-when-kickers-get-iced-with-tidymodels/">looked at when coaches were most likly to ice a kicker</a> where ‘icing a kicker’ means for a defense to call a timeout right before the offense is about to kick a field goal. In this post, I’ll be looking to apply causal inference techniques to see **whether icing the kicker even matters*.</p>
<p>In a perfect world we’d run an A/B test or some type of experiment where some games could be played with the ability to ice the kicker and some without. However, this is unfeasible because the fairness of sports requires that games are played with the same rules.</p>
<p>It would also be easy to just look at the field goal percentage when a kicker was iced vs. wasn’t. However, this would have a lot of selection bias as the situations where a kicker is likely to be iced is different than what might be the normal field goal attempt.</p>
<p>This analysis will follow a similar flow to the <a href="https://github.com/malcolmbarrett/causal_inference_r_workshop">Causal Inference in R Workshop</a> conducted by Lucy McGowan and Malcolm Barrett. And for the data I’ll be reusing the data from my [prior post]((<a href="https://jlaw.netlify.app/2022/01/24/predicting-when-kickers-get-iced-with-tidymodels/" class="uri">https://jlaw.netlify.app/2022/01/24/predicting-when-kickers-get-iced-with-tidymodels/</a>) which 19,072 Field Goal Attempts from College Football between 2013 and 2021. For details on that data and its construction please refer to the [prior post]((<a href="https://jlaw.netlify.app/2022/01/24/predicting-when-kickers-get-iced-with-tidymodels/" class="uri">https://jlaw.netlify.app/2022/01/24/predicting-when-kickers-get-iced-with-tidymodels/</a>).</p>
<div id="what-have-other-analyses-shown" class="section level2">
<h2>What Have Other Analyses Shown?</h2>
<p>This is not the first time this question has been asked:</p>
<ul>
<li>A <a href="https://www.footballstudyhall.com/2018/11/24/18110091/is-icing-the-kicker-really-a-thing">Football Study Hall</a> article found that “Looking at all field goal attempts in Q4 and OT, there were 1070 attempts. 761, or 71% of them were good. Given the condition of whether a kicker was iced or not does seem to make a difference. For kickers who were iced, the number of made field goals drops to 123/196, or 63%, while the kickers who were not iced was 638/874, or 73% were good.”</li>
<li>An <a href="https://www.sbnation.com/2017/11/27/16707624/chris-boswell-icing-the-kicker-nfl-coaches-timeout">SB Nation</a> article, which was actually more of a game recap, has the subtitle “Icing the kicker doesn’t work, but coaches keep on doing it anyway.”.</li>
<li><a href="http://grantland.com/features/icing-kicker-work/">Grantland</a> found that icing the kicker doesn’t work</li>
<li><a href="https://www.espn.com/blog/statsinfo/post/_/id/34217/icing-the-kicker-remains-ineffective-practice">ESPN</a> found that “attempts to ice a kicker at the end of a game actually increased the kicker’s chances of success”</li>
<li>Finally, <a href="https://mixpanel.com/blog/nfl-data-icing-the-kicker/">Mixpanel</a> found " it seems kickers that have been iced are a whole 0.1% less likely to make their kick successfully"</li>
</ul>
<p>To generally, the consensus seems to be that the effect of icing the kicker is somewhere between not effective to potential harmful to the kicking team.</p>
</div>
<div id="what-would-a-naive-analysis-show" class="section level2">
<h2>What Would a Naive Analysis Show?</h2>
<p>I’ll start by doing a really Naive analysis of just looking at data as-is comparing iced to non-iced kickers. To start I’ll load the libraries for this analysis and read in the field goal attempt data from my prior post.</p>
<pre class="r"><code>library(tidyverse)
library(here)
library(gtsummary)
library(broom)
library(survey)
library(rsample)
library(smd)


fg_attempts &lt;- readRDS(here(&#39;content/post/2022-01-17-predicting-when-kickers-get-iced-with-tidymodels/data/fg_attempts.RDS&#39;)) %&gt;%
  transmute(
    regulation_time_remaining,
    attempted_distance,
    drive_is_home_offense = if_else(drive_is_home_offense, 1, 0),
    score_diff,
    prior_miss,
    offense_win_prob,
    is_iced = factor(is_iced, levels = c(0, 1), labels = c(&#39;Not Iced&#39;, &#39;Iced&#39;)),
    fg_made,
    id_play
  )</code></pre>
<p>As a reminder the data contains 19,072 field goals attempts from College Football FBS Regular Season games between 2013
and 2021. For the very naive analysis I’ll just look at the data as-is.</p>
<pre class="r"><code>fg_attempts %&gt;% 
  group_by(`Was Iced` = is_iced) %&gt;% 
  summarize(
    `FG Attempts` = n(),
    `FG Made` = sum(fg_made == T),
    `FG %` = mean(fg_made) %&gt;% scales::percent(accuracy = .1)
  ) %&gt;% 
  knitr::kable(align=&#39;c&#39;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="center">Was Iced</th>
<th align="center">FG Attempts</th>
<th align="center">FG Made</th>
<th align="center">FG %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Not Iced</td>
<td align="center">18268</td>
<td align="center">13882</td>
<td align="center">76.0%</td>
</tr>
<tr class="even">
<td align="center">Iced</td>
<td align="center">804</td>
<td align="center">544</td>
<td align="center">67.7%</td>
</tr>
</tbody>
</table>
<p>From the very Naive data, 76% of non-iced kicks were converted vs. 67.7% of iced kicks for a difference of 8.3%!! This seems like quite a large difference (and if we ran a test of proportions on this it would be statistically significant).</p>
</div>
<div id="a-more-robust-solution" class="section level2">
<h2>A more robust solution</h2>
<p>But comparing iced kicks to non-iced kicks as-is doesn’t make much sense. As many of the articles referenced above state, icing the kicker is something done to increase in the pressure in high-pressure situations like when the kick would determine who wins the game. These types of situations are vastly different than the lower-pressure situations where the majority of field goals occur.</p>
<p>An easy way to determine whether there are differences in the factors that might lead to a field goal being iced is by looking at the <em>standardized mean differences</em> of the other features in the data set to see the extent of the difference between the iced and non-iced attempts.</p>
<p>I’ll be using the <code>tbl_summary()</code> function from <code>{{gtsummary}}</code> to create this table. In the below code, I split the data by <em>is_iced</em>, tell the function to show the mean and standard deviation for all continuous variables, show the percentage for binary variables and each value should be rounded to two digits. The standardized mean difference gets added through the <code>add_difference()</code> function.</p>
<pre class="r"><code>tbl_summary(
  fg_attempts,
  by = &#39;is_iced&#39;,
  include = c(regulation_time_remaining, attempted_distance, 
              drive_is_home_offense, score_diff, prior_miss, offense_win_prob, 
              is_iced),
  statistic = list(all_continuous() ~ &quot;{mean} ({sd})&quot;,
                   all_dichotomous() ~ &quot;{p}%&quot;),
  digits = list(everything() ~ 2)
) %&gt;% 
  add_difference(everything() ~ &quot;smd&quot;)</code></pre>
<div id="fsmqvrzalc" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#fsmqvrzalc .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#fsmqvrzalc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fsmqvrzalc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#fsmqvrzalc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#fsmqvrzalc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fsmqvrzalc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fsmqvrzalc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#fsmqvrzalc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#fsmqvrzalc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#fsmqvrzalc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#fsmqvrzalc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#fsmqvrzalc .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#fsmqvrzalc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#fsmqvrzalc .gt_from_md > :first-child {
  margin-top: 0;
}

#fsmqvrzalc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#fsmqvrzalc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#fsmqvrzalc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#fsmqvrzalc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fsmqvrzalc .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#fsmqvrzalc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fsmqvrzalc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#fsmqvrzalc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#fsmqvrzalc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fsmqvrzalc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fsmqvrzalc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#fsmqvrzalc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fsmqvrzalc .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#fsmqvrzalc .gt_left {
  text-align: left;
}

#fsmqvrzalc .gt_center {
  text-align: center;
}

#fsmqvrzalc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#fsmqvrzalc .gt_font_normal {
  font-weight: normal;
}

#fsmqvrzalc .gt_font_bold {
  font-weight: bold;
}

#fsmqvrzalc .gt_font_italic {
  font-style: italic;
}

#fsmqvrzalc .gt_super {
  font-size: 65%;
}

#fsmqvrzalc .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Not Iced</strong>, N = 18,268<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Iced</strong>, N = 804<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Difference</strong><sup class="gt_footnote_marks">2</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">2,3</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">regulation_time_remaining</td>
<td class="gt_row gt_center">1,936.02 (964.84)</td>
<td class="gt_row gt_center">1,170.94 (898.40)</td>
<td class="gt_row gt_center">0.82</td>
<td class="gt_row gt_center">0.75, 0.89</td></tr>
    <tr><td class="gt_row gt_left">attempted_distance</td>
<td class="gt_row gt_center">35.25 (9.31)</td>
<td class="gt_row gt_center">38.69 (9.85)</td>
<td class="gt_row gt_center">-0.36</td>
<td class="gt_row gt_center">-0.43, -0.29</td></tr>
    <tr><td class="gt_row gt_left">drive_is_home_offense</td>
<td class="gt_row gt_center">51.98%</td>
<td class="gt_row gt_center">50.87%</td>
<td class="gt_row gt_center">0.02</td>
<td class="gt_row gt_center">-0.05, 0.09</td></tr>
    <tr><td class="gt_row gt_left">score_diff</td>
<td class="gt_row gt_center">1.15 (13.57)</td>
<td class="gt_row gt_center">-0.25 (10.94)</td>
<td class="gt_row gt_center">0.11</td>
<td class="gt_row gt_center">0.04, 0.18</td></tr>
    <tr><td class="gt_row gt_left">prior_miss</td>
<td class="gt_row gt_center">13.74%</td>
<td class="gt_row gt_center">17.66%</td>
<td class="gt_row gt_center">-0.11</td>
<td class="gt_row gt_center">-0.18, -0.04</td></tr>
    <tr><td class="gt_row gt_left">offense_win_prob</td>
<td class="gt_row gt_center">0.53 (0.28)</td>
<td class="gt_row gt_center">0.49 (0.24)</td>
<td class="gt_row gt_center">0.12</td>
<td class="gt_row gt_center">0.05, 0.19</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="5">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          Mean (SD); %
          <br />
        </p>
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>2</em>
          </sup>
           
          Standardized Mean Difference
          <br />
        </p>
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>3</em>
          </sup>
           
          CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
<p>When looking at standardized mean differences, generally values less than 0.1 mean there is a adequate balance between the two groups. Between 0.1 and 0.2 is not too alarming, but values greater than 0.2 would indicate a heavy imbalance. In this data, the time remaining, attempted distance show large differences between iced and non-iced attempts.</p>
<p>While there are many mechanisms to correct for the imbalances between the observed groups (Matching, Weighting, Stratification, etc.) I’m going to focus on weighting for this analysis. The process will be:</p>
<ol style="list-style-type: decimal">
<li>Develop Propensity Scores based on other features to predict the probability that a field goal attempt will be iced with logistic regression.</li>
<li>Use the weights to adjust the population of the non-iced group to reflect the iced group. Since I’m looking to determine whether icing the kicker actually matters I want to measure the difference in Field Goal Success Rates for situations when the kicker might be iced. This is called the Average Treatment Effect on the Treated (ATT). This is in contrast to the Average Treatment Effect (ATE), which is this case would measure the causal effect of icing the kicker in general and not just in situations where icing would occur.</li>
<li>Ensure that the post-weighted data are not imbalanced like the pre-weighted data.</li>
<li>Calculate the ATT and bootstrap confidence intervals.</li>
</ol>
<div id="step-1-develop-the-propensity-model" class="section level3">
<h3>Step 1: Develop the Propensity Model</h3>
<p>The first step in developing the weights to make the population more “even” is to develop a propensity score for the treatment. Here I’ll run a logistic regression using <code>glm()</code> to predict where the Field Goal attempt will be iced based on the covariates that were unbalanced from before.</p>
<pre class="r"><code>p_iced &lt;- glm(is_iced ~ regulation_time_remaining + attempted_distance + 
             drive_is_home_offense + I(score_diff^2) + prior_miss + offense_win_prob, 
           data = fg_attempts, 
           family = &#39;binomial&#39;)</code></pre>
<p>These are called propensity models because their output represent the propensity of a given attempt to get iced.</p>
</div>
<div id="step-2-use-the-propensity-scores-to-weight-the-non-iced-field-goal-attempts" class="section level3">
<h3>Step 2: Use the Propensity Scores to weight the non-Iced Field Goal Attempts</h3>
<p>Then by using the <code>augment()</code> function from the <code>{{broom}}</code> package, I can add the predicted values from the model to the <em>fg_attempts</em> data set. The probabilities from this model can be used to re-weight the data in any number of ways. You can make adjust both the best and control to make them look like each other. You can adjust test group to look like the control, and you can weight the control to look like the test.</p>
<p>In this case, since I want to understand the causal effect of icing the kicker on kicks that are likely to be iced, I’ll be re-weighting the control group to look like the test group. Thus, I will be looking for the average treatment effect among the treated (ATT) vs. the overall average treatment effect (ATE).</p>
<p>The formula for re-weighting the population for the ATT is:</p>
<p><span class="math display">\[\Large w_{ATT} = \frac{p_i Z_i}{p_i} + \frac{p_i (1-Z_i)}{1-p_i}\]</span></p>
<p>Where <span class="math display">\[{p_i}\]</span> is the attempt’s propensity to be iced and <span class="math display">\[{Z_i}\]</span> is whether the attempt was <strong>actually</strong> iced. This winds up assigning each attempt in the test group to 1 and will upweight field goal attempts that had higher propensities for being iced.</p>
<pre class="r"><code>weighted_dt &lt;- p_iced %&gt;% 
  augment(type.predict = &quot;response&quot;, data = fg_attempts) %&gt;%
  mutate(
    w_att = ((.fitted * (is_iced==&#39;Iced&#39;))/.fitted) + 
      ((.fitted*(is_iced != &#39;Iced&#39;))/(1-.fitted))
  )</code></pre>
<p>Before showing the effects of the weighting let’s first look at the unweighted propensity scores:</p>
<pre class="r"><code>ggplot(weighted_dt, aes(x = .fitted, fill = is_iced)) + 
  geom_density(alpha = .5) + 
  scale_x_continuous(labels = scales::percent) + 
  #scale_y_log10(labels = scales::comma) + 
  scale_fill_manual(values = c(&#39;Iced&#39; = &#39;green&#39;, &#39;Not Iced&#39; = &#39;blue&#39;)) + 
  labs(x = &quot;P(Icing The Kicker)&quot;,
       y = &quot;&quot;,
       title = &quot;Probability of a FG Attempt Being Iced (Unweighted)&quot;,
       fill = &quot;Kicker Iced?&quot;) + 
  cowplot::theme_cowplot() + 
  theme(
    legend.position = &#39;bottom&#39;,
    legend.justification = &#39;center&#39;
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unweighted_p_scores-1.png" width="100%" /></p>
<p>This makes it very clear that the distributions of propensity to ice differs very heavily between the group that was actually iced and that which was not. Its also nice to see that the group that was actually iced generally have higher propensity scores that those that don’t.</p>
<p>Now let’s look at the distribution of propensity score when taking the weights into account. The distribution of the Iced group is shown in green and is unchanged from the pre and post weightings. On the bottom is the Non-Iced attempts. The overall distribution is shown in grey and the re-weighted distribution is shown in blue. Notice how it more closely reflects the distribution of the iced group.</p>
<pre class="r"><code>weighted_dt %&gt;%
  tidyr::spread(is_iced, .fitted, sep = &quot;_p&quot;) %&gt;%
  ggplot() +
  geom_histogram(bins = 50, aes(is_iced_pIced), alpha = 0.5) + 
  geom_histogram(bins = 50, aes(is_iced_pIced, weight = w_att), fill = &quot;green&quot;, alpha = 0.5) + 
  geom_histogram(bins = 50, alpha = 0.5, aes(x = `is_iced_pNot Iced`, y = -..count..)) + 
  geom_histogram(bins = 50, aes(x = `is_iced_pNot Iced`, weight = w_att, y = -..count..), fill = &quot;blue&quot;, alpha = 0.5) + 
  geom_hline(yintercept = 0, lwd = 0.5) +
  scale_y_continuous(label = abs) +
  scale_x_continuous(label = scales::percent) + 
  labs(title = &quot;Post-Weighted Probability of FG Attempt Being Iced&quot;,
       subtitle = &quot;grey is unweighted distribution&quot;,
       x = &quot;P(Icing the Kicker)&quot;,
       y = &quot;# of Attempts&quot;) + 
  theme_minimal() + 
  geom_rect(aes(xmin = 0.45, xmax = .47, ymin = 5, ymax = 100), fill = &quot;#5DB854&quot;) + 
  geom_text(aes(x = 0.46, y = 50), label = &quot;Iced&quot;, angle = 270, color = &quot;white&quot;) + 
  geom_rect(aes(xmin = 0.45, xmax = .47, ymin = -100, ymax = -5), fill = &quot;#5154B8&quot;) + 
  geom_text(aes(x = 0.46, y = -50), label = &quot;Non-Iced&quot;, angle = 270, color = &quot;white&quot;) + 
  coord_cartesian(ylim = c(-100, 100))</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/weighted_p_scores-1.png" width="100%" /></p>
</div>
<div id="step-3-ensure-the-post-weighted-data-is-no-longer-imbalanced" class="section level3">
<h3>Step 3: Ensure the Post-Weighted Data is no longer Imbalanced</h3>
<p>The next step is to run some diagnostics to make sure that the imbalance that we saw back at the beginning of this post in the standardized mean differences have gone away. I’m going to use the <code>{{survey}}</code> package and the <code>tbl_svysummary()</code> function from <code>{{gtsummary}}</code> to create a survey design object that incorporates the weights that were derived above. The <code>ids = ~ 1</code> code tells the design object that there are no clusters in this.</p>
<pre class="r"><code>svy_des &lt;- svydesign(
  ids = ~ 1,
  data = weighted_dt,
  weights = ~ w_att
)</code></pre>
<p>Then the syntax of <code>tbl_svysummary()</code> is identical to <code>tbl_summary()</code> just it uses the survey design object rather than a data frame. Like with the additional table, I’m adding in the standardized mean difference.</p>
<pre class="r"><code>tbl_svysummary(
  svy_des,
  by = &#39;is_iced&#39;,
  include = c(regulation_time_remaining, attempted_distance, 
              drive_is_home_offense, score_diff, prior_miss, 
              offense_win_prob, is_iced),
  statistic = list(all_continuous() ~ &quot;{mean} ({sd})&quot;,
                   all_dichotomous() ~ &quot;{p}%&quot;),
  digits = list(everything() ~ 2)
) %&gt;% 
  add_difference(everything() ~ &quot;smd&quot;)</code></pre>
<div id="hvqpiymkoi" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#hvqpiymkoi .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hvqpiymkoi .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hvqpiymkoi .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hvqpiymkoi .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hvqpiymkoi .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hvqpiymkoi .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hvqpiymkoi .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hvqpiymkoi .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hvqpiymkoi .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hvqpiymkoi .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hvqpiymkoi .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hvqpiymkoi .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#hvqpiymkoi .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hvqpiymkoi .gt_from_md > :first-child {
  margin-top: 0;
}

#hvqpiymkoi .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hvqpiymkoi .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hvqpiymkoi .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#hvqpiymkoi .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hvqpiymkoi .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#hvqpiymkoi .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hvqpiymkoi .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hvqpiymkoi .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hvqpiymkoi .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hvqpiymkoi .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hvqpiymkoi .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#hvqpiymkoi .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hvqpiymkoi .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#hvqpiymkoi .gt_left {
  text-align: left;
}

#hvqpiymkoi .gt_center {
  text-align: center;
}

#hvqpiymkoi .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hvqpiymkoi .gt_font_normal {
  font-weight: normal;
}

#hvqpiymkoi .gt_font_bold {
  font-weight: bold;
}

#hvqpiymkoi .gt_font_italic {
  font-style: italic;
}

#hvqpiymkoi .gt_super {
  font-size: 65%;
}

#hvqpiymkoi .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Not Iced</strong>, N = 800<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Iced</strong>, N = 804<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Difference</strong><sup class="gt_footnote_marks">2</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">2,3</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">regulation_time_remaining</td>
<td class="gt_row gt_center">1,187.16 (875.67)</td>
<td class="gt_row gt_center">1,170.94 (898.40)</td>
<td class="gt_row gt_center">0.02</td>
<td class="gt_row gt_center">-0.08, 0.12</td></tr>
    <tr><td class="gt_row gt_left">attempted_distance</td>
<td class="gt_row gt_center">38.76 (9.34)</td>
<td class="gt_row gt_center">38.69 (9.85)</td>
<td class="gt_row gt_center">0.01</td>
<td class="gt_row gt_center">-0.09, 0.11</td></tr>
    <tr><td class="gt_row gt_left">drive_is_home_offense</td>
<td class="gt_row gt_center">51.18%</td>
<td class="gt_row gt_center">50.87%</td>
<td class="gt_row gt_center">0.01</td>
<td class="gt_row gt_center">-0.09, 0.10</td></tr>
    <tr><td class="gt_row gt_left">score_diff</td>
<td class="gt_row gt_center">0.63 (11.03)</td>
<td class="gt_row gt_center">-0.25 (10.94)</td>
<td class="gt_row gt_center">0.08</td>
<td class="gt_row gt_center">-0.02, 0.18</td></tr>
    <tr><td class="gt_row gt_left">prior_miss</td>
<td class="gt_row gt_center">17.42%</td>
<td class="gt_row gt_center">17.66%</td>
<td class="gt_row gt_center">-0.01</td>
<td class="gt_row gt_center">-0.10, 0.09</td></tr>
    <tr><td class="gt_row gt_left">offense_win_prob</td>
<td class="gt_row gt_center">0.49 (0.26)</td>
<td class="gt_row gt_center">0.49 (0.24)</td>
<td class="gt_row gt_center">0.00</td>
<td class="gt_row gt_center">-0.10, 0.10</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="5">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          Mean (SD); %
          <br />
        </p>
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>2</em>
          </sup>
           
          Standardized Mean Difference
          <br />
        </p>
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>3</em>
          </sup>
           
          CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
<p>Notice that all of the SMDs are now below the 0.1 threshold.</p>
<p>Another way to visualize the changes in SMDs between is using a Love Plot. Named after Dr. Thomas E. Love, the Love Plot is a way of summarizing covariate balance before and after weighting. In the first code block, I calculate both the weighted and unweighted standardized mean differences using the <code>{{smd}}</code> package. In the <code>smd()</code> code blocks, I pass in each variable, the group variable, and in the case of the weighted version, the weights.</p>
<pre class="r"><code>smds &lt;- weighted_dt %&gt;%
  # Calculate the SMD for Each Variable
  summarise(
    # List Variables to run functions
    across(c(regulation_time_remaining, attempted_distance, 
             drive_is_home_offense, score_diff, prior_miss,
             offense_win_prob),
           # List functions
           list(
             unweighted = ~smd(.x, is_iced, na.rm = T)$estimate, 
             weighted = ~smd(.x, is_iced, w_att, na.rm = T)$estimate 
           ),
           # Assign how the naming will show up in the output
           # Assign placeholder _zzz_ to split on in the next step
           .names = &quot;{.col}_zzz_{.fn}&quot;)
  )

smds %&gt;% 
  pivot_longer( 
    everything(),
    values_to = &quot;SMD&quot;, 
    names_to = c(&quot;variable&quot;, &quot;Method&quot;), 
    names_sep = &quot;_zzz_&quot;
  ) %&gt;%
  ggplot(
    aes(x = abs(SMD), y = variable, group = Method, color = Method)
  ) +  
  geom_line(orientation = &quot;y&quot;) +
  geom_point() + 
  geom_vline(xintercept = 0.1, color = &quot;black&quot;, size = 0.1) + 
  labs(title = &quot;Love Plot Pre/Post Weighting&quot;,
       subtitle = &quot;Post-Weighted Variables are All Balanced&quot;,
       y= &quot;&quot;) + 
  cowplot::theme_cowplot()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>The Love Plot clearly shows that the weighted version of the data has corrected the imbalances that we’ve seen in the unweighted version since all variables are now below 0.1. So it looks like the propensity score weighting</p>
</div>
<div id="step-4-calculate-the-att" class="section level3">
<h3>Step 4: Calculate the ATT</h3>
<p>The final step is to calculate the average treatment effect on the treatment by regressing our outcome variable (Fields Goal Made) by the “treatment” (Whether the kick was iced or not) weighted by the weighting scheme we came up with above.</p>
<pre class="r"><code>final.model &lt;- lm(fg_made ~ is_iced, data = weighted_dt, weights = w_att)

tidy(final.model, conf.int = T) %&gt;%
  select(term, estimate, conf.low, conf.high) %&gt;% 
  mutate(across(where(is.numeric), ~scales::percent(.x, accuracy = .01))) %&gt;% 
  knitr::kable(align = &#39;c&#39;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="center">term</th>
<th align="center">estimate</th>
<th align="center">conf.low</th>
<th align="center">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">(Intercept)</td>
<td align="center">70.51%</td>
<td align="center">69.58%</td>
<td align="center">71.44%</td>
</tr>
<tr class="even">
<td align="center">is_icedIced</td>
<td align="center">-2.85%</td>
<td align="center">-4.16%</td>
<td align="center">-1.54%</td>
</tr>
</tbody>
</table>
<p>From this model the results look like that icing the kicker results in a decreased success rate of 2.85%. The confident intervals from the linear model would suggest that its statistically significant. <em>However</em>, the confidence intervals generated above are overly optimistic as the weights are treated as separate individuals rather than actual weights. In order to get more robust confidence intervals, I’ll use bootstrapping to redo the entire process 1000 times. The following function does the entire process from above (propensity score -&gt; weights -&gt; output model).</p>
<pre class="r"><code>#### Bootstrapping Estimates
fit_ipw &lt;- function(split, ...) { 
  .df &lt;- analysis(split) 
  # fit propensity score model
  
  propensity_model &lt;- glm(
    is_iced ~ regulation_time_remaining + attempted_distance + 
             drive_is_home_offense + I(score_diff^2)  + prior_miss + offense_win_prob, 
    family = binomial(), 
    data = .df
  )
  
  # calculate inverse probability weights
  .df &lt;- propensity_model %&gt;% 
    augment(type.predict = &quot;response&quot;, data = .df) %&gt;%
    mutate(
      w_att = ((.fitted * (is_iced==&#39;Iced&#39;))/.fitted) + 
      ((.fitted*(is_iced != &#39;Iced&#39;))/(1-.fitted))
    )
  
  # fit correctly bootstrapped ipw model
  lm(fg_made ~ is_iced, data = .df, weights = w_att) %&gt;%
    tidy()
}</code></pre>
<p>The bootstrapping will be done using the <code>{{rsample}}</code> package and the <code>bootstraps()</code> function. In the function I ask for 1,000 bootstrapped samples (the apparent option includes a 1001st sample that’s the entire data set). Then I apply the above function to every bootstrapped sample through <code>{{purrr}}</code>’s <code>map()</code> function.</p>
<pre class="r"><code># fit ipw model to bootstrapped samples
tictoc::tic()
set.seed(20220130)
ipw_results &lt;- bootstraps(fg_attempts, 1000, apparent = TRUE) %&gt;% 
  mutate(results = map(splits, fit_ipw))
tictoc::toc()</code></pre>
<pre><code>## 119.29 sec elapsed</code></pre>
<p>Finally, the <code>int_t()</code> function generates confidence intervals from the t-distribution based on the results of the 1,000 bootstrapped samples.</p>
<pre class="r"><code># get t-statistic-based CIs
int_t(ipw_results, results) %&gt;%
  filter(term == &quot;is_icedIced&quot;) %&gt;% 
  select(term, .lower, .estimate, .upper) %&gt;% 
  mutate(across(where(is.numeric), ~scales::percent(.x, accuracy = .01))) %&gt;%
  knitr::kable(align = &#39;c&#39;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="center">term</th>
<th align="center">.lower</th>
<th align="center">.estimate</th>
<th align="center">.upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">is_icedIced</td>
<td align="center">-5.88%</td>
<td align="center">-2.82%</td>
<td align="center">0.50%</td>
</tr>
</tbody>
</table>
<p>From the bootstrapped results, we have the a similar point estimate of -2.82% but the confidence intervals now spans from -5.88% to 0.50% making the results not significantly different from zero.</p>
<p>So in conclusion, we can’t definitively say that icing the kicker is actually harmful to the kicker’s success.</p>
</div>
</div>
